import { Inter } from "next/font/google";
import '../assets/scss/main.scss';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ahmad Online Cadet Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
